#!/bin/bash

#FULL CHR
OFOLDER=/Phasing/PhasingWGS/step8_imputation/concordance_test/binning2

METB="beagle5.4"
METS="shapeit5"

for CHR in 20; do
	#dx run app-swiss-army-knife -iimage_file="/docker/glimpse2_20220825_502047a.tar.gz" -icmd="echo \"chr20 /mnt/project/data/ukb_wgs/unphased/step1_wbic_noval/ukb23352_c20_qc_v1_wbic_no10kgreml_sites.bcf /mnt/project/data/ukb_wgs/phased_shapeit/panels/validation_greml/wgs_ukb23352_c20_qc_v1_all.bcf /mnt/project/Phasing/PhasingWGS/step8_imputation/ligated/imputed_1k_rp_${METB}_chr${CHR}.bcf\" > concordance.txt && GLIMPSE_concordance_v2.0.0 --gt-val --allele-counts --thread 2 --input concordance.txt --output imputed_1k_rp_${METB}_chr${CHR} && rm -f concordance.txt" --instance-type mem1_ssd1_v2_x2 --priority low --name ${METB}_conc_wgs --folder "${OFOLDER}" -y

	#dx run app-swiss-army-knife -iimage_file="/docker/glimpse2_20220825_502047a.tar.gz" -icmd="echo \"chr20 /mnt/project/data/ukb_wgs/unphased/step1_wbic_noval/ukb23352_c20_qc_v1_wbic_no10kgreml_sites.bcf /mnt/project/data/ukb_wgs/phased_shapeit/panels/validation_greml/wgs_ukb23352_c20_qc_v1_all.bcf /mnt/project/Phasing/PhasingWGS/step8_imputation/ligated/imputed_1k_rp_${METS}_chr${CHR}.bcf\" > concordance.txt && GLIMPSE_concordance_v2.0.0 --gt-val --allele-counts --thread 2 --input concordance.txt --output imputed_1k_rp_${METS}_chr${CHR} && rm -f concordance.txt" --instance-type mem1_ssd1_v2_x2 --priority low --name ${METS}_conc_wgs --folder "${OFOLDER}" -y

	#dx run app-swiss-army-knife -iimage_file="/docker/glimpse2_20221002_73decec-dirty.tar.gz" -icmd="echo \"chr20 /mnt/project/Phasing/PhasingWGS/step8_imputation/reference_panels/sites/rp_s1k_shapeit5_chr20.bcf /mnt/project/data/ukb_wgs/phased_shapeit/panels/validation_greml/wgs_ukb23352_c20_qc_v1_all.bcf /mnt/project/Phasing/PhasingWGS/step8_imputation/ligated/imputed_1k_rp_${METB}_chr${CHR}.bcf\" > concordance.txt && GLIMPSE_concordance_v2.0.0 --gt-val --allele-counts --thread 2 --input concordance.txt --output imputed_1k_rp_${METB}_chr${CHR}_rp_af && rm -f concordance.txt" --instance-type mem1_ssd1_v2_x2 --priority low --name ${METB}_conc_wgs --folder "${OFOLDER}" -y

	#dx run app-swiss-army-knife -iimage_file="/docker/glimpse2_20221002_73decec-dirty.tar.gz" -icmd="echo \"chr20 /mnt/project/Phasing/PhasingWGS/step8_imputation/reference_panels/sites/rp_s1k_shapeit5_chr20.bcf /mnt/project/data/ukb_wgs/phased_shapeit/panels/validation_greml/wgs_ukb23352_c20_qc_v1_all.bcf /mnt/project/Phasing/PhasingWGS/step8_imputation/ligated/imputed_1k_rp_${METS}_chr${CHR}.bcf\" > concordance.txt && GLIMPSE_concordance_v2.0.0 --gt-val --allele-counts --thread 2 --input concordance.txt --output imputed_1k_rp_${METS}_chr${CHR}_rp_af && rm -f concordance.txt" --instance-type mem1_ssd1_v2_x2 --priority low --name ${METS}_conc_wgs --folder "/Phasing/PhasingWGS/step8_imputation/concordance_test/" -y

	#dx run app-swiss-army-knife -iimage_file="/docker/glimpse2_20221005_73decec-dirty.tar.gz" -icmd="echo \"chr20 /mnt/project/data/ukb_wgs/unphased/step1_wbic_noval/ukb23352_c20_qc_v1_wbic_no10kgreml_sites.bcf /mnt/project/data/ukb_wgs/phased_shapeit/panels/validation_greml/wgs_ukb23352_c20_qc_v1_all.bcf /mnt/project/Phasing/PhasingWGS/step8_imputation/ligated/imputed_1k_rp_${METB}_chr${CHR}.bcf\" > concordance.txt && GLIMPSE_concordance_v2.0.0 --gt-val --ac-bins 1 5 10 20 50 100 200 500 1000  2000 5000 10000  20000 50000 100000 146754 --input concordance.txt --output imputed_1k_rp_${METB}_chr${CHR}_wbi_af_binning2 && rm -f concordance.txt" --instance-type mem1_ssd1_v2_x2 --priority low --name ${METB}_conc_wgs --folder "${OFOLDER}" -y

	#dx run app-swiss-army-knife -iimage_file="/docker/glimpse2_20221005_73decec-dirty.tar.gz" -icmd="echo \"chr20 /mnt/project/data/ukb_wgs/unphased/step1_wbic_noval/ukb23352_c20_qc_v1_wbic_no10kgreml_sites.bcf /mnt/project/data/ukb_wgs/phased_shapeit/panels/validation_greml/wgs_ukb23352_c20_qc_v1_all.bcf /mnt/project/Phasing/PhasingWGS/step8_imputation/ligated/imputed_1k_rp_${METS}_chr${CHR}.bcf\" > concordance.txt && GLIMPSE_concordance_v2.0.0 --gt-val --ac-bins 1 5 10 20 50 100 200 500 1000  2000 5000 10000  20000 50000 100000 146754 --thread 2 --input concordance.txt --output imputed_1k_rp_${METS}_chr${CHR}_wbi_af_binning2 && rm -f concordance.txt" --instance-type mem1_ssd1_v2_x2 --priority low --name ${METS}_conc_wgs --folder "${OFOLDER}" -y


##########BINNING 2 RP
	#dx run app-swiss-army-knife -iimage_file="/docker/glimpse2_20221005_73decec-dirty.tar.gz" -icmd="echo \"chr20 /mnt/project/Phasing/PhasingWGS/step8_imputation/reference_panels/sites/rp_s1k_shapeit5_chr20.bcf /mnt/project/data/ukb_wgs/phased_shapeit/panels/validation_greml/wgs_ukb23352_c20_qc_v1_all.bcf /mnt/project/Phasing/PhasingWGS/step8_imputation/ligated/imputed_1k_rp_${METB}_chr${CHR}.bcf\" > concordance.txt && GLIMPSE_concordance_v2.0.0 --gt-val --ac-bins 1 5 10 20 50 100 200 500 1000  2000 5000 10000  20000 50000 100000 146754 --thread 2 --input concordance.txt --output imputed_1k_rp_${METB}_chr${CHR}_rp_af_binning2 && rm -f concordance.txt" --instance-type mem1_ssd1_v2_x2 --priority low --name ${METB}_conc_wgs --folder "${OFOLDER}" -y

	#dx run app-swiss-army-knife -iimage_file="/docker/glimpse2_20221005_73decec-dirty.tar.gz" -icmd="echo \"chr20 /mnt/project/Phasing/PhasingWGS/step8_imputation/reference_panels/sites/rp_s1k_shapeit5_chr20.bcf /mnt/project/data/ukb_wgs/phased_shapeit/panels/validation_greml/wgs_ukb23352_c20_qc_v1_all.bcf /mnt/project/Phasing/PhasingWGS/step8_imputation/ligated/imputed_1k_rp_${METS}_chr${CHR}.bcf\" > concordance.txt && GLIMPSE_concordance_v2.0.0 --gt-val --ac-bins 1 5 10 20 50 100 200 500 1000  2000 5000 10000  20000 50000 100000 146754 --thread 2 --input concordance.txt --output imputed_1k_rp_${METS}_chr${CHR}_rp_af_binning2 && rm -f concordance.txt" --instance-type mem1_ssd1_v2_x2 --priority low --name ${METS}_conc_wgs --folder "${OFOLDER}" -y

	dx run app-swiss-army-knife -iimage_file="/docker/glimpse2_20221005_73decec-dirty.tar.gz" -icmd="echo \"chr20 /mnt/project/Phasing/PhasingWGS/step8_imputation/reference_panels/sites/rp_s1k_shapeit5_chr20.bcf /mnt/project/data/ukb_wgs/phased_shapeit/panels/validation_greml/wgs_ukb23352_c20_qc_v1_all.bcf /mnt/project/Phasing/PhasingWGS/step8_imputation/ligated/imputed_1k_rp_hrc_chr${CHR}.bcf\" > concordance.txt && GLIMPSE_concordance_v2.0.0 --gt-val --ac-bins 1 5 10 20 50 100 200 500 1000  2000 5000 10000  20000 50000 100000 146754 --thread 2 --input concordance.txt --output imputed_1k_rp_hrc_chr${CHR}_rp_af_binning2 && rm -f concordance.txt" --instance-type mem1_ssd1_v2_x2 --priority low --name hrc_conc_wgs --folder "${OFOLDER}" -y
done
